[phases.setup]
nixPkgs = ["python3", "gcc", "gnumake", "noto-fonts-cjk-sans", "fontconfig"]

[phases.install]
cmds = ["npm ci --omit=dev", "npm rebuild better-sqlite3 --build-from-source"]

[start]
cmd = "node src/index.js"
